### ISSUE TITLE
Is it possible to decrease the size of the up/down arrows?

### ISSUE THREAD

**Issue by augre** [Dirkster99/NumericUpDownLib#11]

**Comment by Dirkster99** [comment]
It is possible to show or hide the up/down arrows using the [IsIncDecButtonsVisible](https://github.com/Dirkster99/NumericUpDownLib/wiki#isincdecbuttonsvisible) property.

The actual size of the up/down arrows is depends on the Template of the [NumericRepeatButtonControl](https://github.com/Dirkster99/NumericUpDownLib/blob/ae59b5c04ccea7d18fb38347cd2f46f57fb1921f/source/NumericUpDownLib/Base/NumericRepeatButtonControl.xaml#L35). So, you try overriding this with a different height. 

Or a better approach might be changing the Template of the InputBaseDown in order to assign a different path with a different size for the [up](https://github.com/Dirkster99/NumericUpDownLib/blob/fe1c3537ea07a7f24d5c3d3e18bbcc245db74c09/source/NumericUpDownLib/Base/InputBaseUpDown.xaml#L68) and [down](https://github.com/Dirkster99/NumericUpDownLib/blob/fe1c3537ea07a7f24d5c3d3e18bbcc245db74c09/source/NumericUpDownLib/Base/InputBaseUpDown.xaml#L78) control.

Other than its of course possible to extend this functionality but I think re-templating is the best option here since smaller arrows probably call for a different design anyays...?
