### ISSUE TITLE
Setting MinValue has no effect.

### ISSUE THREAD

**Issue by cvdevol** [Dirkster99/NumericUpDownLib#4]
I noticed that this issue was supposed to have been solved, but when I set MinValue to, say 1, the control still goes to zero when using mouse or up/down buttons..

**Comment by Dirkster99** [comment]
Hi, I am not able to verify your problem since you offer no details I could verify.
Please be more specific.

What version of the control are you using?
Do you have a sample project and workflow description to verify the problem?

- I just started the [demo project](https://github.com/Dirkster99/NumericUpDownLib/tree/master/source/TestThemes)
- Set the minimum value for the Byte Slider to say 5
- Tried to decrease to a value less than 5, but the slider stops at the value 5 [OK]

For me, the min value settings works as designed.

**Comment by cvdevol** [comment]
I am using it in a UserControl

in the usercontrol xaml the reference is:

xmlns:nud="clr-namespace:NumericUpDownLib;assembly=NumericUpDownLib"

the NumericUpDown is:

<StackPanel>
<nud:NumericUpDown x:Name="nudMonth" DisplayLength="4" IsReadOnly="False"></nud:NumericUpDown>
.....
</StackPanel>

In the code-behind Sub New I have set:

nudMonth.MinValue = 1
nudMonth.MaxValue = 12
nudMonth.Value = Now.Month

Now when I roll the mouse wheel, or click the down button, the NumericUpDown will not stop at "1", but will go to "0". I have also tried this with UIntegerUpDown and got the same result.

**Comment by cvdevol** [comment]
Here is a simple program to demonstrate:

https://drive.google.com/open?id=1s95K3LRAuOqligT8iQQEibBlKuG4hUev

**Comment by Dirkster99** [comment]
You problem is more a problem of correct initialization than a problem of the control I am afraid. The thing is, that initially, all values are zero:
- MinValue=0, Value=0, MaxValue=0

if you set MinValue=1 or Value = 1 you have:
- **MinValue=1**, Value=0, MaxValue=0
- MinValue=0, **Value=1**, MaxValue=0

which is clearly not conform with the expected constrain: `MinValue <= Value <= MaxValue

Therefore, the control does not let you  reset values in any order you might like. The correct order in your case is to set `MaxValue` first, then the `Value` and then the `MinValue`. Note, that you would have to start with MinValue if you where to use a range that contains only negative values.

So, you should use this sequence instead of the one below (unfortunately sequence matters here):
`<nud:NumericUpDown MaxValue="12" Value="1" MinValue="1" StepSize="1" IsReadOnly="False">`

Wrong Initialization Sequence
`<nud:NumericUpDown MinValue="1" MaxValue="12" StepSize="1" Value="1" IsReadOnly="False">`

You can verify this with the ttached solution:
[NudTestApp.zip](https://github.com/Dirkster99/NumericUpDownLib/files/3342993/NudTestApp.zip)

I also included code that outputs the values of the Numeric Control into the Output Window of Visual Studio.

Using this code in the MainWindow's XAML:
`<nud:NumericUpDown Name="myNum" MaxValue="12" Value="1" MinValue="1" StepSize="1" IsReadOnly="False">
`

with this code in code behind...
```
    Public Sub New()
        AddHandler Me.Loaded, AddressOf Me.LoadedEventHandler
    End Sub

    Private Sub LoadedEventHandler(sender As Object, e As RoutedEventArgs)
        Console.WriteLine("Min: {0} Max: {1} Value: {2}", myNum.MinValue, myNum.MaxValue, myNum.Value)
    End Sub
```

Outputs this: `Min: 1 Max: 12 Value: 1`

You will see a different output if you use the sequence you suggested and you can see that all values are intitially '0' if you execute the same code without the value property assignments.

Lastly, for a range of 12 values you don't need a control based on Numeric values (its a bit of an overkill). Just use int or uint based control and you should by fine for this...

**Comment by cvdevol** [comment]
Yes, that works. Thank you. I assumed it worked like the Windows Forms NumericUpDown, which is not sensitive to the order of the declarations.     On Sunday, June 30, 2019, 7:45:42 AM MST, Dirkster99 <notifications@github.com> wrote:  
 
 
You problem is more a problem of correct initialization than a problem of the control I am afraid. The thing is, that initially, all values are zero:
   
   - MinValue=0, Value=0, MaxValue=0

if you set MinValue=1 or Value = 1 you have:
   
   - MinValue=1, Value=0, MaxValue=0
   - MinValue=0, Value=1, MaxValue=0

which is clearly not conform with the expected constrain: `MinValue <= Value <= MaxValue

Therefore, the control does not let you reset values in any order you might like. The correct order in your case is to set MaxValue first, then the Value and then the MinValue. Note, that you would have to start with MinValue if you where to use a range that contains only negative values.

So, you should use this sequence instead of the one below (unfortunately sequence matters here):
<nud:NumericUpDown MaxValue="12" Value="1" MinValue="1" StepSize="1" IsReadOnly="False">

Wrong Initialization Sequence
<nud:NumericUpDown MinValue="1" MaxValue="12" StepSize="1" Value="1" IsReadOnly="False">

You can verify this with the ttached solution:
NudTestApp.zip

I also included code that outputs the values of the Numeric Control into the Output Window of Visual Studio.

Using this code in the MainWindow's XAML:
<nud:NumericUpDown Name="myNum" MaxValue="12" Value="1" MinValue="1" StepSize="1" IsReadOnly="False"> 

with this code in code behind...
    Public Sub New()        AddHandler Me.Loaded, AddressOf Me.LoadedEventHandler    End Sub    Private Sub LoadedEventHandler(sender As Object, e As RoutedEventArgs)        Console.WriteLine("Min: {0} Max: {1} Value: {2}", myNum.MinValue, myNum.MaxValue, myNum.Value)    End Sub
Outputs this: Min: 1 Max: 12 Value: 1

You will see a different output if you use the sequence you suggested and you can see that all values are intitially '0' if you execute the same code without the value property assignments.

Lastly, for a range of 12 values you don't need a control based on Numeric values (its a bit of an overkill). Just use int or uint based control and you should by fine for this...

**Comment by rwasef1830** [comment]
This still doesn't work when you are using Binding on the Value with a static MinValue even if you have the initialization order correct, because in case of data binding, WPF reads the value from the ViewModel after the control is fully initialized, so it is initialized with a zero value in the beginning, so setting a MinValue more than zero will never work in this case.

The CoerceValue logic needs to be reconsidered as it is completely unsuitable for data binding.

**Comment by Dirkster99** [comment]
@cvdevol @rwasef1830 
Hi Guys,

I've resolved this problem with the Value, Min, and Max settings. This should now work as expected even when using bindings. I even implemented unit tests to proof it:
![Untitled](https://user-images.githubusercontent.com/2129700/80981736-a8cd0300-8e2a-11ea-9e24-8a3274ec978b.png)

Could you please test the current release and let me know what you think about the solution?

Thanx Drk
