### ISSUE TITLE
The arrow of the decrement button is slightly skewed in appearance.

### ISSUE THREAD

**Issue by cvdevol** [Dirkster99/NumericUpDownLib#5]
In AbstractBaseUpDown.xaml I changed:

(Decrement button)
RepeatButtonContent="M 0 0 L 4 4 L 8 0 Z"
to
 RepeatButtonContent="M 0 0 L 3 4 L 6 0 Z"

This makes the arrow more symmetical. Then I changed:

(Increment button)
RepeatButtonContent="M 337.57757568359375,322 C337.57757568359375,322 334,326 334,326 334,326 341,326 341,326 341,326 337.57757568359375,322 337.57757568359375,322 z"
to
RepeatButtonContent="M 0 4 L 6 4 L 3 0 Z"
RepeatButtonContent="M 0 4 L 6 4 L 3 0 Z"

**Comment by Dirkster99** [comment]
Hi Thanks for your suggestion. I changed as requested (as you can verify in the referenced commit above) and published a new version 2.3.1 which should be available on NuGet within an hour (NuGet publications take some extra time since packages are checked for viral code etc before being published to the public).

Thanks Dirk
